import axios from "axios"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from "react"
import styles from '../styles/Home.module.css'
import { createMarkup } from "../utils/createMarkup"
import { getFrontPage } from "../utils/pageUtils/pageUtils"
import Page from '../components/Page/Page';
import Loading from "../components/Layout/Loading/Loading"

const Home: NextPage = () => {

    let [homePageState, setHomePageState] = useState<any>();

    useEffect(() => {

        const getFrontPage = async (): Promise<any> => {
            try {
                const { data } = await axios.get('http://localhost:8000/wp-json/wp/v2/frontpage')
                setHomePageState(data);
                return data;
            } catch (error) {
                console.log(error)
            }
        }

        getFrontPage();

    }, [])


    if (homePageState) {
        return (
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Page title={homePageState.title.rendered} content={homePageState.content.rendered} />

            </div>
        )
    }
    else {
        return <Loading active={true} />
    }
}

export default Home
